[network]
name = 'testnet'
stacks_node_rpc_address = 'https://api.testnet.hiro.so'
deployment_fee_rate = 10

[accounts.deployer]
# Set this locally before deployment.
mnemonic = '<REPLACE_WITH_12_OR_24_WORD_TESTNET_MNEMONIC>'
